services:
  mongo:
    container_name: mongo
    image: mongo:4
    ports:
      - 27017:27017
    networks:
      - internal-net
  transcribe_service:
    container_name: transcribe_service
    build:
      context: ./transcribe_service
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/transcribe
    deploy:
      resources:
        limits:
          memory: "3G"
    networks:
      - ftb-net
      - internal-net
  express:
    container_name: express
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/transcribe
    networks:
      - ftb-net
      - internal-net
  front:
    container_name: front
    build:
      context: ./front
      dockerfile: Dockerfile
    # environment:
    #   - VITE_TRANSCRIBE_API_URL_BASE=http://transcribe_service:5000
    #   - VITE_BACKEND_API_URL=http://express:3000
    ports:
      - 80:3000
    depends_on:
      - express
      - transcribe_service
    networks:
      - ftb-net
networks:
  ftb-net:
    driver: bridge
  internal-net:
    driver: bridge