apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: express
  template:
    metadata:
      labels:
        component: express
    spec:
      containers:
        - name: express
          image: mowmikubek/k8s-backend:v1
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: MONGO_URL